### ISSUE TITLE
PHP8.1+ Required

### ISSUE THREAD

**Issue by Buddyboy-git** [opencart/opencart-3#101]
Should not require PHP 8.  should be put back to 5.4  or create new version of open cart.

**Comment by TheCartpenter** [comment]
One can dream about it all he wants. The truth is, it ain;'t gonna happen: https://github.com/opencart/opencart/discussions/11110#discussioncomment-3043979 .

**Comment by osworx** [comment]
> Should not require PHP 8. should be put back to 5.4 or create new version of open cart.

In which age and country are you living??
Beginning with the 1st of January 2023 (for example), php 7.x is not supported anymore!
Last "stable" release of php 5.x was 5.6 from the 10th January 2019.

And with the publishing of php 7.0 on the 3rd December 2015 (!!) this was announced:
**Support for PHP 5 has been discontinued since 10 Jan 2019.**

And as @TheCartpenter already wrote, php 7.x is deprecated with the 22nd November 2022 (approx. in 6 weeks)

So what do you want?
