### ISSUE TITLE
No releases?

### ISSUE THREAD

**Issue by osworx** [opencart/opencart-3#102]
Just a short question: why is there no release published?

Reason why I ask: more and more people are asking for a php 8.x compatible OpenCart 3.0.3.8
And find at least this repo, but without any release it may be hard to install.
Or at least - if no releases will be published, publish a short description for those, are not firm with Github.

And state in the readme that this repo IS compatible with php 8.x (8.1.x).
And an official fork of the original.

**Comment by TheCartpenter** [comment]
Post these inquiries in the opencart-3 channel instead. Simply look on the commits log, you can see I am still working on the repository almost periodically. I am also waiting for the complete implementation of the new subscriptions and the new affiliate systems from the MB since people using prior versions than PHP 8.1 would encounter the same scenario, they have encountered in the past with the URL Alias via the SEO URLs. This time, an upgrade solution between the old recurring via the new subscriptions is in the works.

I am currently working on the indent for tools compliancy. Close to the year 2023, I think it's about time to consider its importance when it comes to publishing a platform release.

**Comment by TheCartpenter** [comment]
I understand the stress and urgency of the next release. However, while there is no official date release, PHP v7.4x will be deprecated on November 22, 2022. Time is becoming limited as I am dedicating my time on this project many hours a day to meet the industrial requirements. Therefore, the release will have to be before that date is reached. Hopefully @danielkerr will finish both features before then.

**Comment by TheCartpenter** [comment]
By considering that, the latest bug-fixes won't be integrated from the maintenance branch. Granted, extensions may be affected but it's like that for almost any releases. At least, latest solutions will be implemented including the safe side to logout from users' accounts with the help of the new controller/startup profiles as the ways to return the outputs from their methods whereas the maintenance branch does not involve any patching with the ways the return functions need to handle the return variable or user-defined value types.
