### ISSUE TITLE
Edit order does not change currency selected on step 1

### ISSUE THREAD

**Issue by Bary** [opencart/opencart-3#13]
What version of OpenCart are you reporting this for?

3.0.3.8

Describe the bug
There is 5 steps of edit order: on first one change currency, on step 2 you see product(s) with correct new currency and on final step 5 is all visible in new currency (no problem) but clicking save opencart confirm saving on green background but email comes with previous currency, in databse there are not updated columns: currency_id, currency_code, currency_value.

To Reproduce

Go to any order and choose edit ( I did fresh install of 3.0.3.8 made one order in default USD and tried to change that into EUR)
on Step 1 change currency into whatever (EUR on my case)
Save on step 5
See error - no error, but return to that order, still in previous currency
Expected behavior
order in new currency

Server / Test environment (please complete the following information):

Local development? Deployed to a web server? - local docker + web server
Operating system - linux
PHP version - 7.3.32
Apache version - 2.4.51 debian
Browser(s) tested with [e.g. chrome, safari - if applicable] - opera, chrome, edge
Additional context
in the API edit function in catalog/controller/api/order.php and model_checkout_order->editOrder there is nothing that sets the currency when updating an order.

**Comment by Bary** [comment]
Some info here https://github.com/opencart/opencart/issues/10432#issuecomment-1044822732

**Comment by TheCartpenter** [comment]
After testing this, this post has the resolution: https://github.com/opencart/opencart/issues/10891#issuecomment-1137638217 ; an event trigger needs to be created to achieve this. It is not a bug. It is a conceptual decision that's been taken during development.

The reason being; an existing order requires a financial institution (bank) in order to be modified as to approve these transactions whenever a currency value does change for the customer, since the store owner re-affects the order total amount on the invoice. It is good to state from store owners that they'd take the blame and the part of their customers regarding order total amount balance but, in order to do that, it needs to be proved electronically with their final settlement and transaction IDs with their service response.

Your request requires an extension to be, either, opted or developed. Therefore, this commit will now be closed.

**Comment by Bary** [comment]
...Or delete posibility of currency change from step 1 in edit order form in opencart. If there will be no possibility to change currency on step 1 then no issue about it by me and than it can be closed. If someone want it, he can do the extension as you recommend, so first step would be add it again to step one (or to another place) the same way you delete it from next version of opencart. Will you remove it? It make sence, because it you do not, anybody else can report this "bug". Will you create that issue to delete it or do I have?

**Comment by TheCartpenter** [comment]
It's not a bug, you only think it is. By removing the currency option will also prevent extension developers to create their extensions as to store owners to prevent using them on existing orders.

**Comment by Bary** [comment]
I do understand a problems with changing currency, but the rest I do not :(

So you are saying "hey developers here on step 1 is possibility to change currency, but it does not do anything, but it can if you create an extension". I am hoping that there are not any other "easter eggs" in opencart meaning any other fields that are a part of default instalation but do nothing (and you must find it out yourself) and waiting to developer because somebody has an idea to put it there because "what if...sometimes...maybe this field find a developer, it can be very good functionality" now i am joking but who knows ;)

**Comment by TheCartpenter** [comment]
By adding a group of payment options reflecting currencies, what it would involve are the hundreds of thousands of developers who created their extensions to rely on each currency options a payment service provider might use which is not possible since not all payment extension modules do use currency codes. You would, then, be in a better position to have your own currency extension that would also validate your payment while editing an order with the use of Event Triggers reflecting on your order histories on that end. Both ways, you and your customers, would be covered by your payment service provider to cover the balance.
