### ISSUE TITLE
Custom filed missing escap, strange UTF-8 chars in custom fileds

### ISSUE THREAD

**Issue by gegenyrichard** [opencart/opencart-3#162]
Affected version 3.0.3.7
(maybe exist on lower versions)

File (original)
in catalog\model\checkout\order.php
line 4
insert query 3 times account, shipping payment
looks like this

..custom_field = '" . $this->db->escape(isset($data['custom_field']) ? json_encode($data['custom_field']) : '') . "',...
Wrong!

this is the right way
...custom_field = '" . (isset($data['custom_field']) ? $this->db->escape(json_encode($data['custom_field']) : '')) . "',...

Like chars like éáűőúöüóí it save to DB like u00e9u00e1u0151
without slash and json_encode cant' translate it back.

**Comment by TheCartpenter** [comment]
In OC 4, it still displays as the original way. If you want to address this issue in OC 4, whereas nobody else seem to have report it previously, see if that can be added in. Until then, this commit will now be closed.

**Comment by pemaier** [comment]
The custom_field is different but it is not affecting this error.
![image](https://user-images.githubusercontent.com/10166095/235349602-aa5c438c-f7ee-420e-9f6b-46a5936d333c.png)

to be complete that is the 2md difference but also do not affecting that error.
![image](https://user-images.githubusercontent.com/10166095/235349693-b79bb3ad-e1f5-4d57-ba71-dfa2e118077c.png)

**Comment by TheCartpenter** [comment]
Are these results showing since you followed the first post's suggestion for the payment_method, shipping_method, payment_custom_field and shipping_custom_field ?

**Comment by pemaier** [comment]
... there is no other way in a new clean installation.

**Comment by TheCartpenter** [comment]
The previous question is about knowing if you did applied the first post's steps rather than copying manually from PHPMyAdmin which brought the conclusion of both screenshots on the above. Therefore, are these results showing since the first post's suggestions?

opencart-3 contains the same methodologies to insert the values as per the MB, in this case. Please confirm.

**Comment by pemaier** [comment]
The only copy I have done is the copy of payment_method this was empty ... if you download the order table then you get exact the result without any change.

**Comment by TheCartpenter** [comment]
As per the commit on OC 4, could you please try the first post's suggestion and see if it resolves the issue and confirm if it works?

**Comment by TheCartpenter** [comment]
Once these modifications will be changed, could you also confirm which PHP version you are using?

**Comment by pemaier** [comment]
In the moment not - because since yesterday I additionally installed the German language so the order process is not working well anymore. There are differences so the results are not comparable (even they should). I can check this maybe tomorrow again if you like. Sorry.

**Comment by pemaier** [comment]
![image](https://user-images.githubusercontent.com/10166095/235351132-72b0e38e-2652-494b-bc6e-7d652dea5af9.png)

**Comment by TheCartpenter** [comment]
Based on the first post, language packs should not be an issue with the HEX codes being inserted on the database. The related issue you're reporting about seem to be related with thermal operators being inside parentheses, the way it's always been with OC, as opposed of being outside which seem to produce different HEX codes with PHP 8.2+ .

Thanks for posting your PHP version.

**Comment by TheCartpenter** [comment]
In the meantime, if different language packs are being installed on your store, then it means your installation is no longer fresh but rather contains extensions that were also installed afterwards.

**Comment by pemaier** [comment]
You are right the installation from yesterday is wast for further testing.
So what I was doing now ...
I installed a new opencart from master branch
i was doing the basic settings
i used your code suggestion and changed the file
then I tested again ...

Result: The order at all was not saved. (I tried it 3 times.)

**Comment by TheCartpenter** [comment]
Then, store the ```$data``` into a file with a print_r result and post it as an attachment. This issue seem to be caused with UTF-8 whereas a specific or more characters do not match with the escaped characters. There are users who recently begun to post issues about the mount of escaping that is required and I believe this is either server-based or specific scopes these tactics might be required for some reason since other areas are not able to reproduce this issue.

Furthermore, these specific characters could also be caused by language packs other than en-gb since UTF-8 formatting is involved.
