### ISSUE TITLE
AddOrderHistory was not changed in addHistory

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#194]
In 47 controller files in catalog

`$this->model_checkout_order->addOrderHistory`

to

`$this->model_checkout_order->addHistory`

**Comment by condor2** [comment]
and more....
https://github.com/opencart/opencart-3/pull/195

**Comment by TheCartpenter** [comment]
While PRs are in favor, you don't need to create an issue commit before creating a PR about the same subjects. If it's not about a design / planning issue, you don't need to create a new issue. Otherwise, these activities become the real definition of SPAMming. Even I don't do that on the MB repository. Your changes have been merged now.

**Comment by condor2** [comment]
I have created the issue to know what to do.....

Then I have changed my mind and created a PR to help you.......but....
