### ISSUE TITLE
Footer Affiliate is not loaded

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#272]
Possible is not finished

https://github.com/opencart/opencart-3/blob/main/upload/catalog/controller/common/footer.php#L38

**Comment by TheCartpenter** [comment]
Looks like it's been resolved here: https://github.com/opencart/opencart-3/pull/271 . The affiliate status must also be active from the store in order for the affiliate footer link to show.

**Comment by condor2** [comment]
That PR has nothing to do with Affiliate controller not finished.

Before was
`/index.php?route=affiliate/login`

Now is (lik ok4)
`/index.php?route=account/affiliate`

but you get error 
`The page you requested cannot be found!`

Maybe leave issue opened so you know if is finished or not

**Comment by TheCartpenter** [comment]
The reason why this commit was closed was due to the lack of information you provided on the first post. Since the issue has been closed, only then, have you provided more information. I did, however, noticed on more recent issues and PRs that you posted more information compared to this one. Therefore, I will reopen the issue.

**Comment by TheCartpenter** [comment]
There's no ```account/affiliate``` model as described from OC 4 and also why there's no index method in OC 3 releases. I re-added the ```affiliate/login``` link in the footer for now: https://github.com/opencart/opencart-3/commit/b4beab66eb50e0f8488ed4b6038999fd1a07f69a . In the future, I'll look for further features if they apply with these.
