### ISSUE TITLE
[To Do] Missing subscription controller 

### ISSUE THREAD

**Issue by condor2** [opencart/opencart-3#82]
Missing subscription controller from catalog/account

https://github.com/opencart/opencart/blob/master/upload/catalog/controller/account/subscription.php

**Comment by TheCartpenter** [comment]
It's not because it is missing. It's still in the works. By the way, the currency proposal you made from the MB won't work until the OC 3 Engine is converted as for the system framework and a few startup files since the OC 3 Engine doesn't support multi parameters into controllers including the currency($string = '') . We'll have to think of something if we'd want to keep this in.

**Comment by TheCartpenter** [comment]
Afterwards, to work on PHP 8.1 compatibility.

**Comment by TheCartpenter** [comment]
account/subscription has now been added and extension/recurring has been renamed to extension/subscription. Also specified in controllers and libraries accordingly. Will be completing the sale/subscription page shortly.
